environment:
  GIT_REPOSITORY: https://github.com/wheeler-microfluidics/arduino-rpc.git
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"

version: '1.7.35'

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # Exit if no .conda-recipe folder
  - ps: if([System.IO.File]::Exists(".conda-recipe")){Add-AppveyorMessage -Message "No Conda Recipe Found"; -Category "Error"; throw}
  - IF NOT EXIST .conda-recipe exit 1
  - git clone --depth=1 https://github.com/sci-bots/sci-bots-configs.git
  - .\sci-bots-configs\appveyor-install.bat

# Handle build and tests using conda (defined in .conda-recipe/meta.yaml)
build: false
test_script:
  - echo Build Complete

after_test:
  - powershell -executionpolicy remotesigned -File .\sci-bots-configs\appveyor-after-test.ps1